In [5]:
my_list =[1,2,3]

In [6]:
import numpy as np

In [7]:
arr = np.asarray(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_matt = [[1,2,3],[3,4,5],[6,7,8]]

In [10]:
np.asarray(my_matt)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(4,4)

array([[0.96275681, 0.21613929, 0.57988226, 0.57273251],
       [0.22864763, 0.51888776, 0.27707498, 0.13633641],
       [0.49075181, 0.10093878, 0.54892318, 0.44010802],
       [0.45236549, 0.08906721, 0.21112756, 0.91611816]])

In [23]:
np.random.randn(4,4)

array([[ 1.89707743,  1.01780365,  0.09159413, -0.10192712],
       [-0.94156441, -1.52919515, -0.0372371 ,  0.30496753],
       [-1.82348007,  0.10440742,  1.50357203, -0.06106041],
       [-0.49932101,  0.75028081, -0.11117713, -0.36689096]])

In [24]:
np.random.randint(1,100,10)

array([83, 57, 65, 39,  2, 19, 42, 41, 40, 36])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([39,  9, 22, 39, 48, 22,  5, 22,  8, 13])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

48

In [33]:
ranarr.min()

5

In [34]:
ranarr.argmax()

4

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype

dtype('int32')